[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true        # Add this
optimizer = true     # Make sure optimizer is on
optimizer_runs = 200


[rpc_endpoints]
amoy = "https://80002.rpc.thirdweb.com"
base_sepolia = "https://84532.rpc.thirdweb.com"
bsc_testnet = "https://97.rpc.thirdweb.com"

[etherscan]
amoy = { key = "${POLYGONSCAN_KEY}" }
base_sepolia = { key = "${BASESCAN_KEY}" }
bsc_testnet = { key = "${BSCSCAN_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
